#!/usr/bin/env python3
"""
Export normalized longitudinal CT volumes for HCC-TACE latent prediction.

This script consumes the manifests generated by `preprocess_hcc_tace_longitudinal.py`
and writes one preprocessed `.npz` volume per selected CT study. It also writes a
pair manifest that points to the exported source/target tensors.
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Dict, Iterable, List, Sequence, Tuple

import numpy as np
import pydicom
import SimpleITK as sitk


def parse_args() -> argparse.Namespace:
    repo_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description="Export HCC-TACE longitudinal CT volumes.")
    parser.add_argument(
        "--study-manifest",
        type=Path,
        default=repo_root / "datasets" / "processed" / "hcc_tace_longitudinal_ct" / "study_manifest.csv",
        help="Study manifest created by the indexing step.",
    )
    parser.add_argument(
        "--pair-manifest",
        type=Path,
        default=repo_root
        / "datasets"
        / "processed"
        / "hcc_tace_longitudinal_ct"
        / "longitudinal_pairs_adjacent.csv",
        help="Pair manifest to convert into tensor references.",
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        default=repo_root / "datasets" / "processed" / "hcc_tace_longitudinal_ct" / "volumes",
        help="Directory where preprocessed volume tensors will be written.",
    )
    parser.add_argument(
        "--target-spacing",
        type=float,
        nargs=3,
        default=(1.5, 1.5, 3.0),
        metavar=("SX", "SY", "SZ"),
        help="Target voxel spacing in mm as x y z.",
    )
    parser.add_argument(
        "--target-shape",
        type=int,
        nargs=3,
        default=(64, 256, 256),
        metavar=("D", "H", "W"),
        help="Final output shape as depth height width after resampling and crop/pad.",
    )
    parser.add_argument(
        "--hu-window",
        type=int,
        nargs=2,
        default=(-150, 250),
        metavar=("HU_MIN", "HU_MAX"),
        help="HU clip window used before normalization.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Recompute volumes even if the target file already exists.",
    )
    return parser.parse_args()


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def read_csv(path: Path) -> List[Dict[str, str]]:
    with path.open() as f:
        return list(csv.DictReader(f))


def write_csv(path: Path, rows: Iterable[Dict[str, str]], fieldnames: Sequence[str]) -> None:
    with path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def ordered_dicom_files(series_dir: Path) -> List[Path]:
    slices = []
    for dicom_path in series_dir.glob("*.dcm"):
        ds = pydicom.dcmread(
            str(dicom_path),
            stop_before_pixels=True,
            specific_tags=["ImagePositionPatient", "InstanceNumber", "SliceLocation"],
        )
        position = getattr(ds, "ImagePositionPatient", None)
        instance_number = getattr(ds, "InstanceNumber", None)
        slice_location = getattr(ds, "SliceLocation", None)

        if position is not None and len(position) >= 3:
            sort_key = (0, float(position[2]), int(instance_number or 0), dicom_path.name)
        elif slice_location is not None:
            sort_key = (1, float(slice_location), int(instance_number or 0), dicom_path.name)
        else:
            sort_key = (2, int(instance_number or 0), 0, dicom_path.name)

        slices.append((sort_key, dicom_path))

    slices.sort(key=lambda item: item[0])
    return [path for _, path in slices]


def load_ct_image(series_dir: Path) -> sitk.Image:
    files = ordered_dicom_files(series_dir)
    if not files:
        raise RuntimeError(f"No DICOM files found in {series_dir}")

    reader = sitk.ImageSeriesReader()
    reader.SetFileNames([str(path) for path in files])
    reader.MetaDataDictionaryArrayUpdateOn()
    reader.LoadPrivateTagsOn()
    return reader.Execute()


def resample_image(image: sitk.Image, target_spacing_xyz: Tuple[float, float, float]) -> sitk.Image:
    original_spacing = image.GetSpacing()
    original_size = image.GetSize()

    target_spacing = tuple(float(v) for v in target_spacing_xyz)
    target_size = [
        max(1, int(round(original_size[i] * (original_spacing[i] / target_spacing[i]))))
        for i in range(3)
    ]

    resampler = sitk.ResampleImageFilter()
    resampler.SetInterpolator(sitk.sitkLinear)
    resampler.SetOutputSpacing(target_spacing)
    resampler.SetSize(target_size)
    resampler.SetOutputDirection(image.GetDirection())
    resampler.SetOutputOrigin(image.GetOrigin())
    resampler.SetDefaultPixelValue(-1024.0)
    return resampler.Execute(image)


def center_crop_or_pad(volume: np.ndarray, target_shape: Tuple[int, int, int]) -> np.ndarray:
    output = volume
    for axis, target in enumerate(target_shape):
        current = output.shape[axis]
        if current > target:
            start = (current - target) // 2
            end = start + target
            slicer = [slice(None)] * output.ndim
            slicer[axis] = slice(start, end)
            output = output[tuple(slicer)]

    pad_width = []
    for axis, target in enumerate(target_shape):
        current = output.shape[axis]
        deficit = max(0, target - current)
        before = deficit // 2
        after = deficit - before
        pad_width.append((before, after))

    if any(before or after for before, after in pad_width):
        output = np.pad(output, pad_width, mode="constant", constant_values=0.0)

    return output


def normalize_hu(volume: np.ndarray, hu_min: int, hu_max: int) -> np.ndarray:
    volume = np.clip(volume, hu_min, hu_max)
    volume = (volume - hu_min) / float(hu_max - hu_min)
    return volume.astype(np.float32)


def preprocess_volume(
    series_dir: Path,
    target_spacing_xyz: Tuple[float, float, float],
    target_shape_dhw: Tuple[int, int, int],
    hu_window: Tuple[int, int],
) -> Tuple[np.ndarray, Dict[str, object]]:
    image = load_ct_image(series_dir)
    original_spacing_xyz = tuple(float(v) for v in image.GetSpacing())
    original_size_xyz = tuple(int(v) for v in image.GetSize())

    resampled = resample_image(image, target_spacing_xyz)
    array_zyx = sitk.GetArrayFromImage(resampled).astype(np.float32)
    array_dhw = array_zyx
    array_dhw = normalize_hu(array_dhw, hu_window[0], hu_window[1])
    array_dhw = center_crop_or_pad(array_dhw, target_shape_dhw)

    metadata = {
        "original_spacing_xyz": original_spacing_xyz,
        "original_size_xyz": original_size_xyz,
        "resampled_spacing_xyz": tuple(float(v) for v in resampled.GetSpacing()),
        "resampled_size_xyz": tuple(int(v) for v in resampled.GetSize()),
        "final_shape_dhw": tuple(int(v) for v in array_dhw.shape),
        "intensity_range_after_norm": [float(array_dhw.min()), float(array_dhw.max())],
    }
    return array_dhw, metadata


def export_study_volumes(
    repo_root: Path,
    study_rows: List[Dict[str, str]],
    output_root: Path,
    target_spacing_xyz: Tuple[float, float, float],
    target_shape_dhw: Tuple[int, int, int],
    hu_window: Tuple[int, int],
    overwrite: bool,
) -> Dict[Tuple[str, str], Dict[str, str]]:
    exported: Dict[Tuple[str, str], Dict[str, str]] = {}

    for row in study_rows:
        patient_id = row["patient_id"]
        study_uid = row["study_uid"]
        series_rel = row["selected_ct_series_path"]
        series_dir = repo_root / series_rel

        patient_out_dir = output_root / patient_id
        ensure_dir(patient_out_dir)
        volume_path = patient_out_dir / f"{study_uid}.npz"
        metadata_path = patient_out_dir / f"{study_uid}.json"

        if overwrite or not volume_path.exists():
            volume, meta = preprocess_volume(
                series_dir=series_dir,
                target_spacing_xyz=target_spacing_xyz,
                target_shape_dhw=target_shape_dhw,
                hu_window=hu_window,
            )
            np.savez_compressed(volume_path, volume=volume)
            with metadata_path.open("w") as f:
                json.dump(
                    {
                        "patient_id": patient_id,
                        "study_uid": study_uid,
                        "source_series_path": series_rel,
                        **meta,
                    },
                    f,
                    indent=2,
                    sort_keys=True,
                )

        exported[(patient_id, study_uid)] = {
            "volume_npz_path": str(volume_path.resolve().relative_to(repo_root.resolve())),
            "volume_metadata_path": str(metadata_path.resolve().relative_to(repo_root.resolve())),
        }

    return exported


def main() -> None:
    args = parse_args()
    repo_root = Path(__file__).resolve().parents[1]
    ensure_dir(args.output_root)

    study_rows = read_csv(args.study_manifest)
    pair_rows = read_csv(args.pair_manifest)

    exported = export_study_volumes(
        repo_root=repo_root,
        study_rows=study_rows,
        output_root=args.output_root,
        target_spacing_xyz=tuple(args.target_spacing),
        target_shape_dhw=tuple(args.target_shape),
        hu_window=tuple(args.hu_window),
        overwrite=args.overwrite,
    )

    exported_pair_rows: List[Dict[str, str]] = []
    for row in pair_rows:
        source_key = (row["patient_id"], row["source_study_uid"])
        target_key = (row["patient_id"], row["target_study_uid"])
        source_export = exported[source_key]
        target_export = exported[target_key]

        exported_pair_rows.append(
            {
                **row,
                "source_volume_npz_path": source_export["volume_npz_path"],
                "source_volume_metadata_path": source_export["volume_metadata_path"],
                "target_volume_npz_path": target_export["volume_npz_path"],
                "target_volume_metadata_path": target_export["volume_metadata_path"],
            }
        )

    pair_export_manifest = args.output_root.parent / "longitudinal_pairs_adjacent_volumes.csv"
    fieldnames = list(exported_pair_rows[0].keys()) if exported_pair_rows else []
    write_csv(pair_export_manifest, exported_pair_rows, fieldnames)

    summary = {
        "study_manifest": str(args.study_manifest.resolve()),
        "pair_manifest": str(args.pair_manifest.resolve()),
        "output_root": str(args.output_root.resolve()),
        "pair_export_manifest": str(pair_export_manifest.resolve()),
        "target_spacing_xyz": list(map(float, args.target_spacing)),
        "target_shape_dhw": list(map(int, args.target_shape)),
        "hu_window": list(map(int, args.hu_window)),
        "study_count": len(study_rows),
        "pair_count": len(exported_pair_rows),
    }

    with (args.output_root.parent / "volume_export_summary.json").open("w") as f:
        json.dump(summary, f, indent=2, sort_keys=True)

    print(json.dumps(summary, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
